import {
  AlertCircle,
  CalendarDays,
  FileText,
  GraduationCap,
  Thermometer,
} from 'lucide-react';
import type { ComplianceDomain, PriorityAction } from './compliance-model';

export const priorityActionFixtures: PriorityAction[] = [
  {
    id: 'ACT-001',
    title: 'Information sur les allergènes',
    description: '2 fiches allergènes incomplètes',
    category: 'Information client',
    categoryTone: 'brand',
    due: '18 juil. 2026',
    dueTone: 'danger',
    responsible: 'Tam P.',
    initials: 'TP',
    icon: AlertCircle,
    iconTone: 'bg-status-danger-soft text-status-danger',
  },
  {
    id: 'ACT-002',
    title: 'Vérification extincteurs',
    description: 'Vérification annuelle obligatoire',
    category: 'Sécurité ERP',
    categoryTone: 'info',
    due: '2 août 2026',
    dueTone: 'danger',
    responsible: 'Sophie L.',
    initials: 'SL',
    icon: CalendarDays,
    iconTone: 'bg-status-warning-soft text-status-warning',
  },
  {
    id: 'ACT-003',
    title: 'Relevés de température',
    description: '3 relevés de température manquants',
    category: 'Hygiène alimentaire',
    categoryTone: 'success',
    due: "Aujourd'hui",
    dueTone: 'warning',
    responsible: 'Yen N.',
    initials: 'YN',
    icon: Thermometer,
    iconTone: 'bg-status-warning-soft text-status-warning',
  },
  {
    id: 'ACT-004',
    title: 'Mise à jour DUERP',
    description: 'Document à réviser',
    category: 'Personnel & travail',
    categoryTone: 'warning',
    due: '30 août 2026',
    dueTone: 'neutral',
    responsible: 'Tam P.',
    initials: 'TP',
    icon: FileText,
    iconTone: 'bg-surface-muted text-secondary',
  },
  {
    id: 'ACT-005',
    title: 'Formation hygiène alimentaire',
    description: '1 employé sans attestation valide',
    category: 'Hygiène alimentaire',
    categoryTone: 'success',
    due: '14 sept. 2026',
    dueTone: 'neutral',
    responsible: 'Lucas M.',
    initials: 'LM',
    icon: GraduationCap,
    iconTone: 'bg-surface-muted text-secondary',
  },
];

export const complianceDomainFixtures: ComplianceDomain[] = [
  {
    label: 'Hygiène alimentaire',
    score: 88,
    obligations: 24,
    actions: 3,
    tone: 'success',
  },
  {
    label: 'Personnel & travail',
    score: 94,
    obligations: 16,
    actions: 1,
    tone: 'success',
  },
  {
    label: 'Sécurité & ERP',
    score: 82,
    obligations: 18,
    actions: 3,
    tone: 'warning',
  },
  {
    label: 'Information des clients',
    score: 96,
    obligations: 10,
    actions: 0,
    tone: 'success',
  },
  {
    label: 'Données & numérique',
    score: 76,
    obligations: 8,
    actions: 2,
    tone: 'danger',
  },
  {
    label: 'Environnement & déchets',
    score: 90,
    obligations: 10,
    actions: 1,
    tone: 'success',
  },
];
