import type { StockMovement } from './stock-movements-model';

export const stockMovementFixtures: StockMovement[] = [
  {
    id: 'MVT-001',
    date: '12/07/2025',
    time: '09:30',
    type: 'Entrée',
    item: 'Bœuf mariné',
    itemId: 'STK-0048',
    emoji: '🥩',
    category: 'Viandes',
    quantity: 10,
    unit: 'kg',
    zone: 'Chambre froide',
    reference: 'BC-2025-0712-001',
    referenceDetail: 'METRO Poitiers',
    user: 'Sophie L.',
    userInitials: 'SL',
    value: 150,
    status: 'Validé',
    note: 'Réception conforme',
    supplier: 'METRO Poitiers',
    deliveryNote: 'BL-2025-0712-0456',
    shelf: 'Étagère 2',
    purchasePrice: '15,00 € / kg',
  },
  {
    id: 'MVT-002',
    date: '12/07/2025',
    time: '14:10',
    type: 'Sortie',
    item: 'Bœuf mariné',
    itemId: 'STK-0048',
    emoji: '🥩',
    category: 'Viandes',
    quantity: -1.2,
    unit: 'kg',
    zone: 'Cuisine',
    reference: 'CMD-248',
    referenceDetail: 'Vente',
    user: 'Lucas M.',
    userInitials: 'LM',
    value: -18,
    status: 'Validé',
    note: 'Sortie automatique POS',
  },
  {
    id: 'MVT-003',
    date: '12/07/2025',
    time: '18:45',
    type: 'Ajustement',
    item: 'Vermicelles frais',
    itemId: 'STK-0021',
    emoji: '🍜',
    category: 'Pâtes',
    quantity: -0.3,
    unit: 'kg',
    zone: 'Réserve cuisine',
    reference: 'ADJ-2025-0712-001',
    referenceDetail: 'Perte / casse',
    user: 'Sophie L.',
    userInitials: 'SL',
    value: -1.8,
    status: 'Validé',
    note: 'Produit détérioré',
  },
  {
    id: 'MVT-004',
    date: '11/07/2025',
    time: '16:20',
    type: 'Transfert',
    item: 'Lait de coco 400ml',
    itemId: 'STK-0015',
    emoji: '🥫',
    category: 'Épicerie',
    quantity: -6,
    unit: 'unité',
    zone: 'Réserve sèche',
    destination: 'Bar',
    reference: 'TRF-2025-0711-003',
    referenceDetail: 'Transfert interne',
    user: 'Tam P.',
    userInitials: 'TP',
    value: -13.2,
    status: 'Validé',
    note: 'Réapprovisionnement du bar',
  },
  {
    id: 'MVT-005',
    date: '11/07/2025',
    time: '10:15',
    type: 'Entrée',
    item: 'Lait de coco 400ml',
    itemId: 'STK-0015',
    emoji: '🥫',
    category: 'Épicerie',
    quantity: 12,
    unit: 'unité',
    zone: 'Réserve sèche',
    reference: 'BC-2025-0711-002',
    referenceDetail: 'Asia Store',
    user: 'Yen N.',
    userInitials: 'YN',
    value: 31.8,
    status: 'Validé',
    note: 'Réception conforme',
    supplier: 'Asia Store',
    deliveryNote: 'BL-2025-0711-0212',
    shelf: 'Étagère 4',
    purchasePrice: '2,65 € / unité',
  },
  {
    id: 'MVT-006',
    date: '10/07/2025',
    time: '21:30',
    type: 'Sortie',
    item: 'Sauce poisson',
    itemId: 'STK-0012',
    emoji: '🍶',
    category: 'Épicerie',
    quantity: -725,
    unit: 'ml',
    zone: 'Cuisine',
    reference: 'CMD-246',
    referenceDetail: 'Vente',
    user: 'Lucas M.',
    userInitials: 'LM',
    value: -4.35,
    status: 'Validé',
    note: 'Sortie automatique POS',
  },
  {
    id: 'MVT-007',
    date: '10/07/2025',
    time: '08:00',
    type: 'Entrée',
    item: 'Coca-Cola 33cl',
    itemId: 'STK-0056',
    emoji: '🥤',
    category: 'Boissons',
    quantity: 48,
    unit: 'unité',
    zone: 'Bar',
    reference: 'BC-2025-0710-001',
    referenceDetail: 'Promocash',
    user: 'Sophie L.',
    userInitials: 'SL',
    value: 28.8,
    status: 'Validé',
    note: 'Réception conforme',
    supplier: 'Promocash',
    deliveryNote: 'BL-2025-0710-0088',
    shelf: 'Réserve bar',
    purchasePrice: '0,60 € / unité',
  },
  {
    id: 'MVT-008',
    date: '09/07/2025',
    time: '17:45',
    type: 'Ajustement',
    item: 'Salade iceberg',
    itemId: 'STK-0033',
    emoji: '🥬',
    category: 'Légumes',
    quantity: -2,
    unit: 'pièce',
    zone: 'Chambre froide',
    reference: 'ADJ-2025-0709-002',
    referenceDetail: 'Périmé',
    user: 'Tam P.',
    userInitials: 'TP',
    value: -1.2,
    status: 'Validé',
    note: 'Produits périmés',
  },
];
