import type { InventoryItem } from './inventory-model';

export const inventoryItemFixtures: InventoryItem[] = [
  {
    id: 'STK-0048',
    name: 'Bœuf mariné',
    emoji: '🥩',
    unit: 'kg',
    category: 'Viandes',
    location: 'Chambre froide',
    stock: 8.4,
    minimum: 5,
    maximum: 15,
    value: 126,
    status: 'Disponible',
    movementDay: "Aujourd'hui",
    movementTime: '09:30',
    supplier: 'Métro',
    packaging: 'Carton de 10 kg',
    purchasePrice: '15,00 € / kg',
    barcode: '3760123456789',
  },
  {
    id: 'STK-0021',
    name: 'Vermicelles frais',
    emoji: '🍜',
    unit: 'kg',
    category: 'Pâtes',
    location: 'Réserve cuisine',
    stock: 3.2,
    minimum: 4,
    maximum: 12,
    value: 19.2,
    status: 'Stock faible',
    movementDay: 'Il y a 2 h',
    movementTime: '14:10',
    supplier: 'Asia Marché',
    packaging: 'Sac de 5 kg',
    purchasePrice: '6,00 € / kg',
    barcode: '3760123456796',
  },
  {
    id: 'STK-0015',
    name: 'Lait de coco 400ml',
    emoji: '🥫',
    unit: 'unité',
    category: 'Épicerie',
    location: 'Réserve sèche',
    stock: 0,
    minimum: 6,
    maximum: 36,
    value: 0,
    status: 'Rupture',
    movementDay: 'Hier',
    movementTime: '18:45',
    supplier: 'Métro',
    packaging: 'Carton de 12',
    purchasePrice: '2,10 € / unité',
    barcode: '3760123456802',
  },
  {
    id: 'STK-0033',
    name: 'Salade iceberg',
    emoji: '🥬',
    unit: 'pièce',
    category: 'Légumes',
    location: 'Chambre froide',
    stock: 6,
    minimum: 6,
    maximum: 20,
    value: 3,
    status: 'Disponible',
    movementDay: "Aujourd'hui",
    movementTime: '08:50',
    supplier: 'Primeur local',
    packaging: 'Caisse de 10',
    purchasePrice: '0,50 € / pièce',
    barcode: '3760123456819',
  },
  {
    id: 'STK-0012',
    name: 'Sauce poisson',
    emoji: '🍶',
    unit: 'ml',
    category: 'Épicerie',
    location: 'Réserve sèche',
    stock: 725,
    minimum: 500,
    maximum: 2000,
    value: 4.35,
    status: 'Disponible',
    movementDay: "Aujourd'hui",
    movementTime: '08:20',
    supplier: 'Asia Marché',
    packaging: 'Bouteille 725 ml',
    purchasePrice: '4,35 € / bouteille',
    barcode: '3760123456826',
  },
  {
    id: 'STK-0056',
    name: 'Coca-Cola 33cl',
    emoji: '🥤',
    unit: 'unité',
    category: 'Boissons',
    location: 'Bar',
    stock: 48,
    minimum: 24,
    maximum: 96,
    value: 28.8,
    status: 'Disponible',
    movementDay: "Aujourd'hui",
    movementTime: '09:15',
    supplier: 'Coca-Cola',
    packaging: 'Pack de 24',
    purchasePrice: '0,60 € / unité',
    barcode: '3760123456833',
  },
  {
    id: 'STK-0009',
    name: 'Œufs calibre M',
    emoji: '🥚',
    unit: 'pièce',
    category: 'Produits frais',
    location: 'Chambre froide',
    stock: 12,
    minimum: 30,
    maximum: 90,
    value: 2.4,
    status: 'Stock faible',
    movementDay: 'Hier',
    movementTime: '17:30',
    supplier: 'Ferme du Centre',
    packaging: 'Plateau de 30',
    purchasePrice: '0,20 € / pièce',
    barcode: '3760123456840',
  },
  {
    id: 'STK-0037',
    name: 'Riz jasmin 5kg',
    emoji: '🍚',
    unit: 'kg',
    category: 'Épicerie',
    location: 'Réserve sèche',
    stock: 18,
    minimum: 10,
    maximum: 40,
    value: 27,
    status: 'Disponible',
    movementDay: 'Hier',
    movementTime: '16:12',
    supplier: 'Asia Marché',
    packaging: 'Sac de 5 kg',
    purchasePrice: '1,50 € / kg',
    barcode: '3760123456857',
  },
];
