import type { RestaurantTable } from './tables-model';

export const restaurantTableFixtures: readonly RestaurantTable[] = [
  {
    id: '01',
    room: 'Salle principale',
    seats: 4,
    availability: 'Disponible',
    shape: 'square',
  },
  {
    id: '02',
    room: 'Salle principale',
    seats: 4,
    availability: 'Disponible',
    shape: 'square',
  },
  {
    id: '03',
    room: 'Salle principale',
    seats: 4,
    availability: 'Réservée',
    reservation: '20:00 · 4 pers.',
    shape: 'square',
  },
  {
    id: '04',
    room: 'Salle principale',
    seats: 6,
    availability: 'Indisponible',
    shape: 'rectangle',
  },
  {
    id: '05',
    room: 'Salle principale',
    seats: 2,
    availability: 'Réservée',
    reservation: '19:30 · 2 pers.',
    shape: 'round',
  },
  {
    id: '06',
    room: 'Salle principale',
    seats: 6,
    availability: 'Disponible',
    shape: 'rectangle',
  },
  {
    id: 'T1',
    room: 'Terrasse',
    seats: 2,
    availability: 'Disponible',
    shape: 'round',
  },
  {
    id: 'T2',
    room: 'Terrasse',
    seats: 4,
    availability: 'Réservée',
    reservation: '12:30 · 4 pers.',
    shape: 'round',
  },
  {
    id: 'T3',
    room: 'Terrasse',
    seats: 4,
    availability: 'Disponible',
    shape: 'square',
  },
  {
    id: 'B1',
    room: 'Bar',
    seats: 2,
    availability: 'Disponible',
    shape: 'rectangle',
  },
  {
    id: 'B2',
    room: 'Bar',
    seats: 2,
    availability: 'Indisponible',
    shape: 'rectangle',
  },
];
