import type { Supplier } from './suppliers-model';

export const supplierFixtures: Supplier[] = [
  {
    id: 'F-0001',
    name: 'METRO Poitiers',
    logo: 'M',
    logoTone: 'bg-status-info text-inverse',
    categories: 'Épicerie, Boissons, Produits frais',
    phone: '05 49 45 12 12',
    email: 'poitiers@metro.fr',
    payment: '30 jours',
    delivery: '24–48h',
    lastOrderDate: '12/07/2025',
    lastOrderAmount: '356,20 €',
    status: 'Actif',
    zone: 'Poitiers et alentours',
    address: '15 Rue des Frères Lumière, 86000 Poitiers',
    minimum: '150,00 €',
    shipping: 'Gratuit dès 300,00 €',
    monthlyPurchases: '356,20 €',
    annualPurchases: '4 256,80 €',
    orderCount: '18',
  },
  {
    id: 'F-0002',
    name: 'Promocash Poitiers',
    logo: 'PC',
    logoTone: 'bg-status-danger text-inverse',
    categories: 'Viandes, Produits surgelés',
    phone: '05 49 62 34 34',
    email: 'poitiers@promocash.fr',
    payment: '30 jours',
    delivery: '24h',
    lastOrderDate: '10/07/2025',
    lastOrderAmount: '542,80 €',
    status: 'Actif',
    zone: 'Poitiers',
    address: '8 Avenue de la Loge, 86000 Poitiers',
    minimum: '100,00 €',
    shipping: '15,00 €',
    monthlyPurchases: '542,80 €',
    annualPurchases: '6 890,00 €',
    orderCount: '24',
  },
  {
    id: 'F-0003',
    name: 'Asia Store',
    logo: 'AS',
    logoTone: 'bg-status-danger-soft text-status-danger',
    categories: 'Produits asiatiques, Épicerie',
    phone: '05 49 88 10 29',
    email: 'contact@asia-store.fr',
    payment: 'Comptant',
    delivery: 'Enlèvement',
    lastOrderDate: '08/07/2025',
    lastOrderAmount: '128,60 €',
    status: 'Actif',
    zone: 'Poitiers',
    address: '21 Rue Carnot, 86000 Poitiers',
    minimum: '50,00 €',
    shipping: 'Enlèvement',
    monthlyPurchases: '385,80 €',
    annualPurchases: '3 840,40 €',
    orderCount: '31',
  },
  {
    id: 'F-0004',
    name: 'Fresh Express',
    logo: 'F',
    logoTone: 'bg-status-success text-inverse',
    categories: 'Fruits & Légumes',
    phone: '06 12 34 56 78',
    email: 'commande@fresh.fr',
    payment: '7 jours',
    delivery: 'Quotidienne',
    lastOrderDate: "Aujourd'hui",
    lastOrderAmount: '78,40 €',
    status: 'Actif',
    zone: 'Vienne',
    address: '4 Route du Marché, 86180 Buxerolles',
    minimum: '40,00 €',
    shipping: 'Gratuit',
    monthlyPurchases: '940,80 €',
    annualPurchases: '9 480,00 €',
    orderCount: '96',
  },
  {
    id: 'F-0005',
    name: 'Boucherie du Centre',
    logo: 'BC',
    logoTone: 'bg-primary text-inverse',
    categories: 'Viandes fraîches',
    phone: '05 49 41 22 33',
    email: 'contact@boucherie-centre.fr',
    payment: '15 jours',
    delivery: 'À la demande',
    lastOrderDate: '05/07/2025',
    lastOrderAmount: '215,90 €',
    status: 'Actif',
    zone: 'Poitiers',
    address: '6 Place du Marché, 86000 Poitiers',
    minimum: '80,00 €',
    shipping: 'Gratuit',
    monthlyPurchases: '680,20 €',
    annualPurchases: '7 920,00 €',
    orderCount: '42',
  },
  {
    id: 'F-0006',
    name: 'Paprec',
    logo: 'P',
    logoTone: 'bg-status-info-soft text-status-info',
    categories: 'Emballages, Jetables',
    phone: '05 49 01 02 03',
    email: 'poitiers@paprec.com',
    payment: '30 jours',
    delivery: '48h',
    lastOrderDate: '01/07/2025',
    lastOrderAmount: '96,30 €',
    status: 'Inactif',
    zone: 'Nouvelle-Aquitaine',
    address: 'Zone industrielle République, 86000 Poitiers',
    minimum: '100,00 €',
    shipping: '20,00 €',
    monthlyPurchases: '0,00 €',
    annualPurchases: '1 245,00 €',
    orderCount: '7',
  },
  {
    id: 'F-0007',
    name: 'LDC',
    logo: 'LDC',
    logoTone: 'bg-status-danger text-inverse',
    categories: 'Poulet, Volaille',
    phone: '05 49 18 77 66',
    email: 'commande@ldc.fr',
    payment: '30 jours',
    delivery: '48h',
    lastOrderDate: '28/06/2025',
    lastOrderAmount: '482,10 €',
    status: 'Actif',
    zone: 'Vienne',
    address: '12 Route de Châtellerault, 86000 Poitiers',
    minimum: '200,00 €',
    shipping: 'Gratuit dès 400,00 €',
    monthlyPurchases: '964,20 €',
    annualPurchases: '11 480,00 €',
    orderCount: '36',
  },
];
